services:
  db:
    image: postgres:17.6
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2

  web:
    build: .
    command: gunicorn -c gunicorn.conf.py telepad.wsgi:application
    volumes:
      - ./core:/app
      - ./media:/media
      - ./static:/static
    env_file: .env
    depends_on:
      - db
      - redis
       
  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/media
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - web

  celery:
    build: .
    command: celery -A telepad worker -l info
    volumes:
      - ./core:/app
      - ./media:/media
    env_file: .env
    depends_on:
      - db
      - redis
      - web
  bot:
    build: .
    command: python bot.py
    volumes:
      - ./media:/media
      - ./telegram:/app
    env_file: .env
    depends_on:
      - redis
      - db

volumes:
  db_data:
