services:
  db:
    image: postgres:17.6
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default_network

  redis:
    image: redis:8.2
    networks:
      - default_network

  web:
    build: .
    command: gunicorn -c gunicorn.conf.py telepad.wsgi:application
    volumes:
      - ./core:/app
      - ./media:/media
      - ./static:/static
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - default_network
       
  nginx:
    build: ./frontend
    volumes:
      - ./media:/media
      - ./static:/static
    depends_on:
      - web
    networks:
      default_network:
        aliases:
          - nginx

  celery:
    build: .
    command: celery -A telepad worker -l info
    volumes:
      - ./core:/app
      - ./media:/media
    env_file: .env
    depends_on:
      - db
      - redis
      - web
    networks:
      - default_network

  bot:
    build: .
    command: python bot.py
    volumes:
      - ./media:/media
      - ./telegram:/app
    env_file: .env
    depends_on:
      - redis
      - db
    networks:
      - default_network

  cloudflared:
    image: cloudflare/cloudflared:2025.9.1
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - nginx
    networks:
      default_network:
        aliases:
          - cloudflared
      
volumes:
  db_data:

networks:
  default_network:
    driver: bridge